[package]
name = "margium"
version = "0.1.0"
edition = "2024"

[dependencies]
cairo-rs = "0.21.5"
glib = "0.21.5"
gtk4 = "0.10.3"
pango = "0.21.5"
poppler-rs = "0.25.0"
lopdf = "0.39.0"
chrono = "0.4.43"
uuid = "1.20.0"
async-channel = "2.5.0"
mathjax_svg = "3.1.2"
librsvg = "2.61.3"
